In [1]:
import pandas as pd
import numpy as np

### Sample text 

In [2]:
doc1 = 'I am Hamza Ali'
doc2 = 'I am from Mansehra'
doc3 = 'I am Computer Engineer'
doc4 = 'I love Pakistan'
doc5 = 'Pakistan Ziandabad'
doc6 = 'Alhamdulillah'

### Creating DataFrame

In [3]:
df = pd.DataFrame({'Text' : [doc1, doc2, doc3, doc4, doc5, doc6], 'Output' : [1,1,1,2,2,3]})
df

Text  Output
0          I am Hamza Ali       1
1      I am from Mansehra       1
2  I am Computer Engineer       1
3         I love Pakistan       2
4      Pakistan Ziandabad       2
5           Alhamdulillah       3

### Using countvector() class for bag of words

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
CV = CountVectorizer()

In [14]:
BOW = CV.fit_transform(df["Text"])
BOW.shape

(6, 11)

In [15]:
CV.vocabulary_

{'am': 2,
 'hamza': 6,
 'ali': 1,
 'from': 5,
 'mansehra': 8,
 'computer': 3,
 'engineer': 4,
 'love': 7,
 'pakistan': 9,
 'ziandabad': 10,
 'alhamdulillah': 0}

In [16]:
BOW[0].toarray()

array([[0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0]], dtype=int64)

### By adding new words have no effect on vocabulary size means that no problem of OOV

In [17]:
CV.transform(['I offer Prayers']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

### N-Grams for text Representation
Actually bag of words are just uni-gram 

In [25]:
CV2  = CountVectorizer(ngram_range=(2,2))
BOW2 = CV2.fit_transform(df["Text"])

In [32]:
BOW2

<6x8 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [27]:
CV2.vocabulary_

{'am hamza': 2,
 'hamza ali': 5,
 'am from': 1,
 'from mansehra': 4,
 'am computer': 0,
 'computer engineer': 3,
 'love pakistan': 6,
 'pakistan ziandabad': 7}

In [33]:
BOW2[0].toarray()

array([[0, 0, 1, 0, 0, 1, 0, 0]], dtype=int64)